GET http://localhost:5000/categories

###

GET http://localhost:5000/questions?page=1

###

# 422 when question notfound
DELETE http://localhost:5000/questions/99999

###

DELETE http://localhost:5000/questions/2

###

# Create success
POST http://localhost:5000/questions
content-type: application/json

{
    "question": "question content",
    "answer": "answer content",
    "difficulty": 4,
    "category": 5
}

###

# 422: Create fail when missed field
POST http://localhost:5000/questions
content-type: application/json

{
    "question": "question content",
    "difficulty": 4,
    "category": 5
}

###

POST http://localhost:5000/questions/search
content-type: application/json

{
    "searchTerm": "title"
}

###

GET http://localhost:5000/categories/1/questions

###

# 404: No questions
POST http://localhost:5000/quizzes
content-type: application/json

{
    "previous_questions": [20, 22, 21],
    "quiz_category": {
        "type": "Science",
        "id": 1
    }
}

###

POST http://localhost:5000/quizzes
content-type: application/json

{
    "previous_questions": [20],
    "quiz_category": {
        "type": "Science",
        "id": 1
    }
}
